### ISSUE TITLE
iOS not receiving push notifications through FCM.

### ISSUE THREAD

**Issue by ganttastic** [Ingenio/flutter_pubnub#15]
Thank you for spending time to write this! I'm currently integrating it into a Flutter real-time bidding application and ran into an issue --

Because I'm using Flutter, it's going to be easier to use Firebase Cloud Messaging instead of APNS on it's own for push notifications. Currently, Android is receiving notifications as intended, but iOS is not. I was able to finally able to narrow down the issue -- It looks like the current version used of the PubNub SDK for iOS is lowercasing the FCM instance ID before sending to PubNub causing a mismatch when trying to send a push. (Check out `PubNub+APNS.m` Line 176).  After removing the various `.lowercaseString`s, I am now seeing the correct channel registration and push notifications appearing on iOS.

It looks like the latest version of the PubNub SDK (4.12.0) corrects this issue. Let me know if you need any help or if you'd like me to make a PR to update. Thanks again!

**Comment by EgorLogachev** [comment]
@ganttastic your PR was merged. Flutter package will be updated soon.

**Comment by EgorLogachev** [comment]
@ganttastic  thank you!
