### ISSUE TITLE
App crashes when building apk without --no-shrink

### ISSUE THREAD

**Issue by royibernthal** [Ingenio/flutter_pubnub#17]
I'm using flutter_pubnub 0.2.0.

I'm building a fat APK using `flutter build apk`.
The app is installed and works great, until the moment I'm trying to initialize flutter_pubnub.

```
_pubNub = PubNub(
        PubNubConfig(
            'publish_key',
            'subscribe_key',
            uuid: 'uuid'
        )
    );

    await _pubNub.subscribeToChannelGroups([ 'channelGroup' ]); //this line results in crashing in release mode if built without --no-shrink
```

I got the following stack trace from crashlytics:

```
Fatal Exception: java.lang.NullPointerException: throw with null exception
       at b.f.a.l.c.f.b(:3)
       at b.f.a.k.i$d.a(:209)
       at b.f.a.k.i$d.a(:2)
       at b.f.a.h.a$a.a(:45)
       at g.h$b$a$a.run(:37)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

When I'm building with `--no-shrink` the app doesn't crash and everything works as it's supposed to:
`flutter build apk --no-shrink`

It feels like it might be related to the following issue:
https://github.com/Ingenio/flutter_pubnub/issues/12

However you mentioned it's already been solved, so either it's not related, or the issue wasn't entirely solved :)

**Comment by EgorLogachev** [comment]
@royibernthal Hi, thanks for your report, please provide your mapping.txt file. It will help me to deobfuscate error in stack trace an localise error.

**Comment by royibernthal** [comment]
@EgorLogachev Hi, sure, attached.

[mapping.txt](https://github.com/Ingenio/flutter_pubnub/files/4276807/mapping.txt)

**Comment by EgorLogachev** [comment]
@royibernthal you are right, your problem relates to [#12](https://github.com/Ingenio/flutter_pubnub/issues/12) issue. We haven't update flutter_pubnub package version on pub.dev yet. You will be mentioned when we make update with fix. It will be tomorrow or even today. For now [here required fix](https://github.com/Ingenio/flutter_pubnub/commit/e744c8e7cf462be96238e5f2af6f3e765606854d).

**Comment by olivierbrand** [comment]
I have just pushed 0.3.1 that includes to proguard rules additions. Please test it and let us know if that fixed the issue

**Comment by royibernthal** [comment]
Yup, fixed. Thanks for resolving the issue quickly.
