### ISSUE TITLE
Failed to build iOS app, Error output from Xcode build:

### ISSUE THREAD

**Issue by Gursewak-Uppal** [Ingenio/flutter_pubnub#2]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET flutter_pubnub OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/apple/Projects/Flutter/Exp/PubNub/flutter_pubnub-master/ios/Classes/PubnubPlugin.m:151:12: error: property 'stripMobilePayload' not found on object of type 'PNConfiguration *'
        config.stripMobilePayload = NO;
               ^
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by EgorLogachev** [comment]
Issue was solved. Check latest version of plugin. Thank you for feedback.
